### ISSUE TITLE
Tibia 11

### ISSUE THREAD

**Issue by rmobis** [Tibia-WindBot/WindBot-Docs#52]
Okey, so, we just started adding documentation about WindBot for Tibia 11 on the tibia-11 branch and once it's out of beta we plan on merging it back to the master branch. Here's what we gotta do:

- [x] Prepare structure for separate Tibia 11 entries
- [ ] Actually add all new entries
- [x] Release WindBot for Tibia 11
- [ ] Fix link in inventoryitem, inventoryitem.count, inventoryitem.id, spellinfo.learned, servercount to point to announcement thread
- [ ] Migrate the changes to the correct structure after release; special attention to the new types, as those couldn't be properly separated from the old Tibia 10 section.

**Comment by XtrmJosh** [comment]
Entries for variables, types added. Issue encountered adding type which is the build system only goes 3 levels deep. Solution was a temporary hack where we added the only property (.learned) to the non-Tibia-11 specific section. Due to that there is a big red warning box on that property so hopefully users won't mistake it.

**Comment by XtrmJosh** [comment]
tibia-11/types does not parse newlines. Need to investigate how to handle this. Looks like it might need a template change so will leave that for later. For now it's single line.

**Comment by XtrmJosh** [comment]
inventoryitem, inventoryitem.count and inventoryitem.id also have the warning mentioned above. The links there will need updating. I'll add a list to the first post in the issue.

**Comment by XtrmJosh** [comment]
The following have now all been added but they are subject to some questions:

> New Functions
> servercount(itemid, ignoreequips) - will tell how many items of id itemid you have on your inventory (even with closed backpacks). If you pass true to ignoreequips it won't count your equipment.
> depotcount(itemid) - will tell how many items of id itemid you have on your depot. You must open market before using this function!
> gettool(tooltype) - returns the itemid for tooltype, where tooltype can be 'rope', 'shovel', 'machete', or 'pick'. It will always prioritize the item you chose in Cavebot, if available, otherwise it will pick any available, or 0 (if no tool was found).
> cloudmessage(message) - will send a message to WindCloud, which will be displayed in your character's profile.
> 
> 
> New Iterators
> foreach depotitem - iterates through all the items on your depot, and shows how much you have of each item. You must open market before using this. Properties: .id and .count
> foreach inventoryitem - iterates through each item on your inventory and shows how much you have of each item. Properties: .id and .count
> 
> 
> New Spell Property
> .learned - returns true if your character have already learned this spell, false otherwise.
> 
> 
> New Variables
> $money - tells how much money you have on your inventory
> $foodtime - tells how many milliseconds you still have of food
> $hungry - returns true if your character is hungry, false otherwise
> $mlevelbase - your base magic level, without item modifiers
> $fistbase - your base fist fighting, without item modifiers
> $clubbase - your base club fighting, without item modifiers
> $swordbase - your base sword fighting, without item modifiers
> $axebase - your base axe fighting, without item modifiers
> $distancebase - your base distance fighting, without item modifiers
> $shieldingbase - your base shielding, without item modifiers
> $fishingbase - your base fishing, without item modifiers
> $hasservercount - returns true if the server you are playing at supports servercount(...), false otherwise.

Questions put forward are:

> does servercount() in wb11 not use server messages any more?
> does servercount() and depotcount() accept both item id and item name?

If servercount no longer uses server messages, we can simply replace the old servercount function with the new one and it Should Just Work ©. If they both accept item ID and item name (which they should) again it should be fine. If the latter is not true we are breaking backwards compatibility so we need to be very cautious.

**Comment by XtrmJosh** [comment]
Iterators still live with the standard Tibia 10 stuff because they won't work under the tibia 11 folder. @rmobis thinks they will but I think the template would need changing...

How it should look:

http://i.imgur.com/CLIL6NM.png

How it does look:

http://i.imgur.com/CqgtUzs.png

**Comment by rmobis** [comment]
Oh, the iterators thingy is probably because I did something wrong on the
initial structure. Will check it soon.

**Comment by XtrmJosh** [comment]
Both servercount and depotcount take ID or item name meaning servercount won't break backwards compatibility. Might be worth noting that it will first try server count using the new method, if it fails it will look in server log for using one of message, and it fails there it will return 0...

**Comment by rmobis** [comment]
I believe this needs to be updated according to latest betas.

**Comment by rmobis** [comment]
Closing as the project is being archived
