### ISSUE TITLE
$inpz not documented or missused instead of $pzone

### ISSUE THREAD

**Issue by UltraMC** [Tibia-WindBot/WindBot-Docs#53]
Can't find any documentation occurances of $inpz (it's not documented or not existing, can't verify as have no access to software licence)

In other hand $pzone is documented https://www.tibiawindbot.com/docs.html#variables-pzone

Was partially addressed at https://github.com/Tibia-WindBot/WindBot-Docs/commit/d7bac04880a0fa217de2da97c6e90bbe990c0f4d

**Comment by rmobis** [comment]
It seems `$inpz` used to exist on (very) early WindBot times but was then removed, so I think your PR solves all problems related to this.

Thanks for the contribution.
